//************************************************************************************
//************************************************************************************
//
// App Name:  AE-Helper
// Release:  v. 0.5
// Author:  J.W. Hall
//
// Created:  December 3, 2021
// Last Updated:  December 6, 2021
//
// Description:
// Assists in the creation and rendering of MPK movie files using the dataset
// generated by the Majime app.
//
//************************************************************************************
//************************************************************************************

//+ include dom
//+ include data
//+ include ui
//+ include parseTime
//+ include parseClassifier
//+ include parseDay
//+ include queue
//+ include jobBuilder
//+ include eventManager
//+ include factory


//Factory.populateRenderQueue();
Factory.render_each_job();


////////////////////////////////////////////////////////////////////////////////
// app module
////////////////////////////////////////////////////////////////////////////////
var AppController = (function(data, jobBuilder, queue, dom) {
  function populateRenderQueue() {
    for(var i = 0; i < data.ui.length; i++) {
      queue.createJob(
        data.file[i],
        dom.masters[jobBuilder.getShow(data.ui[i].toLowerCase())]
      );
    }
  }

  return {
    populateRenderQueue: populateRenderQueue,
  }
})(data, jobBuilder, queue, dom);

////////////////////////////////////////////////////////////////////////////////
// app module -- end
////////////////////////////////////////////////////////////////////////////////
